// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type serviceLBServiceBackendKey struct {
	_        structs.HostLayout
	Frontend serviceLBServiceFrontendKey
	Slot     uint32
}

type serviceLBServiceBackendValue struct {
	_       structs.HostLayout
	Address uint32
	Port    uint16
	Flags   uint8
	Pad     uint8
	Tenant  [64]int8
}

type serviceLBServiceFrontendKey struct {
	_        structs.HostLayout
	Address  uint32
	Port     uint16
	Protocol uint8
	Pad      uint8
}

type serviceLBServiceFrontendValue struct {
	_            structs.HostLayout
	BackendCount uint32
	Flags        uint32
}

type serviceLBServiceSocketRevnatKey struct {
	_              structs.HostLayout
	SocketCookie   uint64
	BackendAddress uint32
	BackendPort    uint16
	Pad            uint16
}

type serviceLBServiceSocketRevnatValue struct {
	_               structs.HostLayout
	FrontendAddress uint32
	FrontendPort    uint16
	Protocol        uint8
	Pad             uint8
}

// loadServiceLB returns the embedded CollectionSpec for serviceLB.
func loadServiceLB() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ServiceLBBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load serviceLB: %w", err)
	}

	return spec, err
}

// loadServiceLBObjects loads serviceLB and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*serviceLBObjects
//	*serviceLBPrograms
//	*serviceLBMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadServiceLBObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadServiceLB()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// serviceLBSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type serviceLBSpecs struct {
	serviceLBProgramSpecs
	serviceLBMapSpecs
	serviceLBVariableSpecs
}

// serviceLBProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type serviceLBProgramSpecs struct {
	SeteraServiceConnect4     *ebpf.ProgramSpec `ebpf:"setera_service_connect4"`
	SeteraServiceGetpeername4 *ebpf.ProgramSpec `ebpf:"setera_service_getpeername4"`
	SeteraServiceRecvmsg4     *ebpf.ProgramSpec `ebpf:"setera_service_recvmsg4"`
	SeteraServiceSendmsg4     *ebpf.ProgramSpec `ebpf:"setera_service_sendmsg4"`
}

// serviceLBMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type serviceLBMapSpecs struct {
	SvcBackend    *ebpf.MapSpec `ebpf:"svc_backend"`
	SvcFrontend   *ebpf.MapSpec `ebpf:"svc_frontend"`
	SvcSockRevnat *ebpf.MapSpec `ebpf:"svc_sock_revnat"`
	SvcSockStats  *ebpf.MapSpec `ebpf:"svc_sock_stats"`
}

// serviceLBVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type serviceLBVariableSpecs struct {
}

// serviceLBObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadServiceLBObjects or ebpf.CollectionSpec.LoadAndAssign.
type serviceLBObjects struct {
	serviceLBPrograms
	serviceLBMaps
	serviceLBVariables
}

func (o *serviceLBObjects) Close() error {
	return _ServiceLBClose(
		&o.serviceLBPrograms,
		&o.serviceLBMaps,
	)
}

// serviceLBMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadServiceLBObjects or ebpf.CollectionSpec.LoadAndAssign.
type serviceLBMaps struct {
	SvcBackend    *ebpf.Map `ebpf:"svc_backend"`
	SvcFrontend   *ebpf.Map `ebpf:"svc_frontend"`
	SvcSockRevnat *ebpf.Map `ebpf:"svc_sock_revnat"`
	SvcSockStats  *ebpf.Map `ebpf:"svc_sock_stats"`
}

func (m *serviceLBMaps) Close() error {
	return _ServiceLBClose(
		m.SvcBackend,
		m.SvcFrontend,
		m.SvcSockRevnat,
		m.SvcSockStats,
	)
}

// serviceLBVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadServiceLBObjects or ebpf.CollectionSpec.LoadAndAssign.
type serviceLBVariables struct {
}

// serviceLBPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadServiceLBObjects or ebpf.CollectionSpec.LoadAndAssign.
type serviceLBPrograms struct {
	SeteraServiceConnect4     *ebpf.Program `ebpf:"setera_service_connect4"`
	SeteraServiceGetpeername4 *ebpf.Program `ebpf:"setera_service_getpeername4"`
	SeteraServiceRecvmsg4     *ebpf.Program `ebpf:"setera_service_recvmsg4"`
	SeteraServiceSendmsg4     *ebpf.Program `ebpf:"setera_service_sendmsg4"`
}

func (p *serviceLBPrograms) Close() error {
	return _ServiceLBClose(
		p.SeteraServiceConnect4,
		p.SeteraServiceGetpeername4,
		p.SeteraServiceRecvmsg4,
		p.SeteraServiceSendmsg4,
	)
}

func _ServiceLBClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed servicelb_x86_bpfel.o
var _ServiceLBBytes []byte
