// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcFirewallIfaceConfig struct {
	_             structs.HostLayout
	DefaultAction uint32
	Flags         uint32
}

type tcFirewallPktStats struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
	Dropped   uint64
}

type tcFirewallVethTenant struct {
	_           structs.HostLayout
	Tenant      [64]int8
	VethIfindex uint32
}

// loadTcFirewall returns the embedded CollectionSpec for tcFirewall.
func loadTcFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcFirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcFirewall: %w", err)
	}

	return spec, err
}

// loadTcFirewallObjects loads tcFirewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcFirewallObjects
//	*tcFirewallPrograms
//	*tcFirewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcFirewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallSpecs struct {
	tcFirewallProgramSpecs
	tcFirewallMapSpecs
	tcFirewallVariableSpecs
}

// tcFirewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallProgramSpecs struct {
	TcFirewallEgress  *ebpf.ProgramSpec `ebpf:"tc_firewall_egress"`
	TcFirewallIngress *ebpf.ProgramSpec `ebpf:"tc_firewall_ingress"`
}

// tcFirewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallMapSpecs struct {
	TcIfaceCfg *ebpf.MapSpec `ebpf:"tc_iface_cfg"`
	TcPodIDs   *ebpf.MapSpec `ebpf:"tc_podIDs"`
	TcStats    *ebpf.MapSpec `ebpf:"tc_stats"`
}

// tcFirewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallVariableSpecs struct {
	MyTenant *ebpf.VariableSpec `ebpf:"my_tenant"`
}

// tcFirewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallObjects struct {
	tcFirewallPrograms
	tcFirewallMaps
	tcFirewallVariables
}

func (o *tcFirewallObjects) Close() error {
	return _TcFirewallClose(
		&o.tcFirewallPrograms,
		&o.tcFirewallMaps,
	)
}

// tcFirewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallMaps struct {
	TcIfaceCfg *ebpf.Map `ebpf:"tc_iface_cfg"`
	TcPodIDs   *ebpf.Map `ebpf:"tc_podIDs"`
	TcStats    *ebpf.Map `ebpf:"tc_stats"`
}

func (m *tcFirewallMaps) Close() error {
	return _TcFirewallClose(
		m.TcIfaceCfg,
		m.TcPodIDs,
		m.TcStats,
	)
}

// tcFirewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallVariables struct {
	MyTenant *ebpf.Variable `ebpf:"my_tenant"`
}

// tcFirewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallPrograms struct {
	TcFirewallEgress  *ebpf.Program `ebpf:"tc_firewall_egress"`
	TcFirewallIngress *ebpf.Program `ebpf:"tc_firewall_ingress"`
}

func (p *tcFirewallPrograms) Close() error {
	return _TcFirewallClose(
		p.TcFirewallEgress,
		p.TcFirewallIngress,
	)
}

func _TcFirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcfirewall_x86_bpfel.o
var _TcFirewallBytes []byte
