// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcFirewallIfaceConfig struct {
	_             structs.HostLayout
	DefaultAction uint32
	Flags         uint32
}

type tcFirewallPktStats struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
	Dropped   uint64
}

type tcFirewallServiceBackendKey struct {
	_        structs.HostLayout
	Frontend tcFirewallServiceFrontendKey
	Slot     uint32
}

type tcFirewallServiceBackendValue struct {
	_       structs.HostLayout
	Address uint32
	Port    uint16
	Flags   uint8
	Pad     uint8
	Tenant  [64]int8
}

type tcFirewallServiceFrontendKey struct {
	_        structs.HostLayout
	Address  uint32
	Port     uint16
	Protocol uint8
	Pad      uint8
}

type tcFirewallServiceFrontendValue struct {
	_            structs.HostLayout
	BackendCount uint32
	Flags        uint32
}

type tcFirewallServicePacketFlowKey struct {
	_               structs.HostLayout
	ClientAddress   uint32
	FrontendAddress uint32
	ClientPort      uint16
	FrontendPort    uint16
	Protocol        uint8
	Pad             [3]uint8
}

type tcFirewallServicePacketFlowValue struct {
	_              structs.HostLayout
	BackendAddress uint32
	BackendPort    uint16
	BackendFlags   uint8
	Pad            uint8
	LastSeenNs     uint64
}

type tcFirewallServicePacketRevnatKey struct {
	_              structs.HostLayout
	BackendAddress uint32
	ClientAddress  uint32
	BackendPort    uint16
	ClientPort     uint16
	Protocol       uint8
	Pad            [3]uint8
}

type tcFirewallServicePacketRevnatValue struct {
	_               structs.HostLayout
	FrontendAddress uint32
	FrontendPort    uint16
	Pad             uint16
	LastSeenNs      uint64
}

type tcFirewallVethTenant struct {
	_           structs.HostLayout
	Tenant      [64]int8
	VethIfindex uint32
}

// loadTcFirewall returns the embedded CollectionSpec for tcFirewall.
func loadTcFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcFirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcFirewall: %w", err)
	}

	return spec, err
}

// loadTcFirewallObjects loads tcFirewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcFirewallObjects
//	*tcFirewallPrograms
//	*tcFirewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcFirewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallSpecs struct {
	tcFirewallProgramSpecs
	tcFirewallMapSpecs
	tcFirewallVariableSpecs
}

// tcFirewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallProgramSpecs struct {
	TcFirewallEgress  *ebpf.ProgramSpec `ebpf:"tc_firewall_egress"`
	TcFirewallIngress *ebpf.ProgramSpec `ebpf:"tc_firewall_ingress"`
}

// tcFirewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallMapSpecs struct {
	SvcBackend     *ebpf.MapSpec `ebpf:"svc_backend"`
	SvcFrontend    *ebpf.MapSpec `ebpf:"svc_frontend"`
	SvcPktFlow     *ebpf.MapSpec `ebpf:"svc_pkt_flow"`
	SvcPktRevnat   *ebpf.MapSpec `ebpf:"svc_pkt_revnat"`
	SvcPktStats    *ebpf.MapSpec `ebpf:"svc_pkt_stats"`
	TcIfaceCfg     *ebpf.MapSpec `ebpf:"tc_iface_cfg"`
	TcPodIDs       *ebpf.MapSpec `ebpf:"tc_podIDs"`
	TcStats        *ebpf.MapSpec `ebpf:"tc_stats"`
	TcVxlanIfindex *ebpf.MapSpec `ebpf:"tc_vxlan_ifindex"`
}

// tcFirewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcFirewallVariableSpecs struct {
	MyIsDefault *ebpf.VariableSpec `ebpf:"my_is_default"`
	MyTenant    *ebpf.VariableSpec `ebpf:"my_tenant"`
}

// tcFirewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallObjects struct {
	tcFirewallPrograms
	tcFirewallMaps
	tcFirewallVariables
}

func (o *tcFirewallObjects) Close() error {
	return _TcFirewallClose(
		&o.tcFirewallPrograms,
		&o.tcFirewallMaps,
	)
}

// tcFirewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallMaps struct {
	SvcBackend     *ebpf.Map `ebpf:"svc_backend"`
	SvcFrontend    *ebpf.Map `ebpf:"svc_frontend"`
	SvcPktFlow     *ebpf.Map `ebpf:"svc_pkt_flow"`
	SvcPktRevnat   *ebpf.Map `ebpf:"svc_pkt_revnat"`
	SvcPktStats    *ebpf.Map `ebpf:"svc_pkt_stats"`
	TcIfaceCfg     *ebpf.Map `ebpf:"tc_iface_cfg"`
	TcPodIDs       *ebpf.Map `ebpf:"tc_podIDs"`
	TcStats        *ebpf.Map `ebpf:"tc_stats"`
	TcVxlanIfindex *ebpf.Map `ebpf:"tc_vxlan_ifindex"`
}

func (m *tcFirewallMaps) Close() error {
	return _TcFirewallClose(
		m.SvcBackend,
		m.SvcFrontend,
		m.SvcPktFlow,
		m.SvcPktRevnat,
		m.SvcPktStats,
		m.TcIfaceCfg,
		m.TcPodIDs,
		m.TcStats,
		m.TcVxlanIfindex,
	)
}

// tcFirewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallVariables struct {
	MyIsDefault *ebpf.Variable `ebpf:"my_is_default"`
	MyTenant    *ebpf.Variable `ebpf:"my_tenant"`
}

// tcFirewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcFirewallPrograms struct {
	TcFirewallEgress  *ebpf.Program `ebpf:"tc_firewall_egress"`
	TcFirewallIngress *ebpf.Program `ebpf:"tc_firewall_ingress"`
}

func (p *tcFirewallPrograms) Close() error {
	return _TcFirewallClose(
		p.TcFirewallEgress,
		p.TcFirewallIngress,
	)
}

func _TcFirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcfirewall_x86_bpfel.o
var _TcFirewallBytes []byte
