apiVersion: v1
kind: Pod
metadata:
  name: b2
  namespace: default
  annotations:
    setera.com/tenant: "two"
spec:
  containers:
  - name: b2
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector:
    setera.com.tenant.two: "Enabled"
  restartPolicy: Always