apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
  annotations:
    misokube.com/tenant: "one"
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  nodeSelector:
    misokube.com.tenant.one: "Enabled"
  restartPolicy: Always