apiVersion: v1
kind: ServiceAccount
metadata:
  name: stub-daemon-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: stub-daemon-cluster-role
rules:
- apiGroups:
  - setera.com
  resources:
  - tenants
  - nodestores
  - tenants/status
  - nodestores/status
  verbs:
  - list
  - watch
  - create
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - pods
  - configmaps
  - events
  verbs:
  - create
  - list
  - watch
  - get
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: stub-daemon-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stub-daemon-cluster-role
subjects:
- kind: ServiceAccount
  name: stub-daemon-service-account
  namespace: default
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tenantcni-config
  namespace: default
  labels:
    tier: node
    app: cni
data:
  cni-conf.json: |
   {
      "cniVersion": "0.4.0",
      "name": "setera",
      "type": "setera"
    }
  net-conf.json: |
    {
      "PodCIDR": "10.244.0.0/24",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    tier: node
    app: stub-daemon
  name: stub-daemon
spec:
  selector:
    matchLabels:
      app: stub-daemon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stub-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: stub-daemon-service-account
      initContainers:
      - name: install-cni-plugin
        image: cni-uds-stub:dev
        command: 
        - cp
        args:
        - -f
        - /cni
        - /opt/cni/bin/setera
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: cni-uds-stub:dev
        command: 
        - cp
        args:
        - -f
        - /etc/cni/cni-conf.json
        - /etc/cni/net.d/10-tenantcni.conf
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: tenantcni
          mountPath: /etc/cni/
      containers:
      - image: daemon-uds-stub:dev
        name: daemon
        command:
        - /stub-daemon
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace 
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SOCKET
          value: /var/run/setera/setera.sock
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        volumeMounts:
        - name: cni-socket-stub
          mountPath: /var/run/setera
      volumes:
        - name: cni-socket-stub
          hostPath:
            path: /var/run/setera
            type: DirectoryOrCreate
        - name: var-lib-cni-uds-stub
          hostPath:
            path: /var/lib/cni/cni-uds-stub
        - name: cni-plugin
          hostPath:
            path: /opt/cni/bin
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: tenantcni
          configMap:
            name: tenantcni-config
        - name: tenantcni-cfg
          configMap:
            name: tenantcni-config      
