controlPlane:
    statefulSet:
      pods:
        annotations:
          setera.com/tenant: "default"
      scheduling:
        nodeSelector:
          setera.com.tenant.default: "Enabled"
      persistence:
        volumeClaim:
          enabled: false