controlPlane:
    statefulSet:
      pods:
        labels:
          misokube.com/tenant: "default"
      scheduling:
        nodeSelector:
          misokube.com/tenant.default: "true"
      persistence:
        volumeClaim:
          enabled: false
