// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type nodeRouterIfaceConfig struct {
	_             structs.HostLayout
	DefaultAction uint32
	Flags         uint32
}

type nodeRouterPktStats struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
	Dropped   uint64
}

type nodeRouterVethTenant struct {
	_           structs.HostLayout
	Tenant      [64]int8
	VethIfindex uint32
}

// loadNodeRouter returns the embedded CollectionSpec for nodeRouter.
func loadNodeRouter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NodeRouterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nodeRouter: %w", err)
	}

	return spec, err
}

// loadNodeRouterObjects loads nodeRouter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nodeRouterObjects
//	*nodeRouterPrograms
//	*nodeRouterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNodeRouterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNodeRouter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nodeRouterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodeRouterSpecs struct {
	nodeRouterProgramSpecs
	nodeRouterMapSpecs
	nodeRouterVariableSpecs
}

// nodeRouterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodeRouterProgramSpecs struct {
	TcNodeEgress  *ebpf.ProgramSpec `ebpf:"tc_node_egress"`
	TcNodeIngress *ebpf.ProgramSpec `ebpf:"tc_node_ingress"`
}

// nodeRouterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodeRouterMapSpecs struct {
	TcIfaceCfg *ebpf.MapSpec `ebpf:"tc_iface_cfg"`
	TcPodIDs   *ebpf.MapSpec `ebpf:"tc_podIDs"`
	TcStats    *ebpf.MapSpec `ebpf:"tc_stats"`
}

// nodeRouterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nodeRouterVariableSpecs struct {
	MyTenant *ebpf.VariableSpec `ebpf:"my_tenant"`
}

// nodeRouterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNodeRouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodeRouterObjects struct {
	nodeRouterPrograms
	nodeRouterMaps
	nodeRouterVariables
}

func (o *nodeRouterObjects) Close() error {
	return _NodeRouterClose(
		&o.nodeRouterPrograms,
		&o.nodeRouterMaps,
	)
}

// nodeRouterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNodeRouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodeRouterMaps struct {
	TcIfaceCfg *ebpf.Map `ebpf:"tc_iface_cfg"`
	TcPodIDs   *ebpf.Map `ebpf:"tc_podIDs"`
	TcStats    *ebpf.Map `ebpf:"tc_stats"`
}

func (m *nodeRouterMaps) Close() error {
	return _NodeRouterClose(
		m.TcIfaceCfg,
		m.TcPodIDs,
		m.TcStats,
	)
}

// nodeRouterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNodeRouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodeRouterVariables struct {
	MyTenant *ebpf.Variable `ebpf:"my_tenant"`
}

// nodeRouterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNodeRouterObjects or ebpf.CollectionSpec.LoadAndAssign.
type nodeRouterPrograms struct {
	TcNodeEgress  *ebpf.Program `ebpf:"tc_node_egress"`
	TcNodeIngress *ebpf.Program `ebpf:"tc_node_ingress"`
}

func (p *nodeRouterPrograms) Close() error {
	return _NodeRouterClose(
		p.TcNodeEgress,
		p.TcNodeIngress,
	)
}

func _NodeRouterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed noderouter_x86_bpfel.o
var _NodeRouterBytes []byte
