// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpFirewallFwRuleKey struct {
	_         structs.HostLayout
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	Protocol  uint8
	SrcPrefix uint8
	DstPrefix uint8
	Pad       uint8
}

type xdpFirewallFwRuleVal struct {
	_       structs.HostLayout
	Action  uint32
	_       [4]byte
	Packets uint64
	Bytes   uint64
}

type xdpFirewallIfaceConfig struct {
	_             structs.HostLayout
	DefaultAction uint32
	Flags         uint32
}

type xdpFirewallLpmV4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type xdpFirewallPktStats struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
	Dropped   uint64
}

// loadXdpFirewall returns the embedded CollectionSpec for xdpFirewall.
func loadXdpFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpFirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdpFirewall: %w", err)
	}

	return spec, err
}

// loadXdpFirewallObjects loads xdpFirewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpFirewallObjects
//	*xdpFirewallPrograms
//	*xdpFirewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdpFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpFirewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFirewallSpecs struct {
	xdpFirewallProgramSpecs
	xdpFirewallMapSpecs
	xdpFirewallVariableSpecs
}

// xdpFirewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFirewallProgramSpecs struct {
	XdpFirewall *ebpf.ProgramSpec `ebpf:"xdp_firewall"`
}

// xdpFirewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFirewallMapSpecs struct {
	XdpFwRules         *ebpf.MapSpec `ebpf:"xdp_fw_rules"`
	XdpFwRulesCIDR_dst *ebpf.MapSpec `ebpf:"xdp_fw_rules_CIDR_dst"`
	XdpFwRulesCIDR_src *ebpf.MapSpec `ebpf:"xdp_fw_rules_CIDR_src"`
	XdpIfaceAction     *ebpf.MapSpec `ebpf:"xdp_iface_action"`
	XdpIfaceCfg        *ebpf.MapSpec `ebpf:"xdp_iface_cfg"`
	XdpStats           *ebpf.MapSpec `ebpf:"xdp_stats"`
}

// xdpFirewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpFirewallVariableSpecs struct {
}

// xdpFirewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFirewallObjects struct {
	xdpFirewallPrograms
	xdpFirewallMaps
	xdpFirewallVariables
}

func (o *xdpFirewallObjects) Close() error {
	return _XdpFirewallClose(
		&o.xdpFirewallPrograms,
		&o.xdpFirewallMaps,
	)
}

// xdpFirewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFirewallMaps struct {
	XdpFwRules         *ebpf.Map `ebpf:"xdp_fw_rules"`
	XdpFwRulesCIDR_dst *ebpf.Map `ebpf:"xdp_fw_rules_CIDR_dst"`
	XdpFwRulesCIDR_src *ebpf.Map `ebpf:"xdp_fw_rules_CIDR_src"`
	XdpIfaceAction     *ebpf.Map `ebpf:"xdp_iface_action"`
	XdpIfaceCfg        *ebpf.Map `ebpf:"xdp_iface_cfg"`
	XdpStats           *ebpf.Map `ebpf:"xdp_stats"`
}

func (m *xdpFirewallMaps) Close() error {
	return _XdpFirewallClose(
		m.XdpFwRules,
		m.XdpFwRulesCIDR_dst,
		m.XdpFwRulesCIDR_src,
		m.XdpIfaceAction,
		m.XdpIfaceCfg,
		m.XdpStats,
	)
}

// xdpFirewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFirewallVariables struct {
}

// xdpFirewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpFirewallPrograms struct {
	XdpFirewall *ebpf.Program `ebpf:"xdp_firewall"`
}

func (p *xdpFirewallPrograms) Close() error {
	return _XdpFirewallClose(
		p.XdpFirewall,
	)
}

func _XdpFirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpfirewall_x86_bpfel.o
var _XdpFirewallBytes []byte
